[package]
name = "reqwest-app"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
scraper = "0.18"
anyhow = "1.0"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
